### ISSUE TITLE
Wrongfull placement of Classified Document 1: Orders of the Day

### ISSUE THREAD

**Issue by CaelynInc** [lordfiSh/sniperelite5maps#1]
I found the document on an entirely different location. Added are screenshots of the placement, the map, and the document. 

(I hope this is the right place to mention this 😇) 

![725e9704-6ca1-4d0b-85d2-203690e6aecf.png](https://user-images.githubusercontent.com/29156243/173120288-3048d3a4-ff4b-4c2f-b857-568c32793f54.png)![716e5ac9-6aef-4956-9cae-15ee61a25667.png](https://user-images.githubusercontent.com/29156243/173120309-496aaacf-0140-4dfb-af44-c3d5b4e7b759.png)![49a31128-8198-441e-be30-15a4f9c3632c.png](https://user-images.githubusercontent.com/29156243/173120328-761ab293-c349-4b57-971e-09cb9e3f4bcb.png)

**Comment by AtomCrafty** [comment]
Both are correct. Documents 1, 4 and 5 on this map exist multiple times. In my local version I have all of them marked, but I haven't pushed the changes yet. Thanks for reminding me :)

And yes, GitHub issues are the right place to notify us about errors, submitting new markers is easier with a simple right-click on the map.

**Comment by AtomCrafty** [comment]
Should be fixed with 70236585fb147e82425a383044c268c9b7de3502, @lordfiSh could you update the live version?

**Comment by CaelynInc** [comment]
> Both are correct. Documents 1, 4 and 5 on this map exist multiple times. In my local version I have all of them marked, but I haven't pushed the changes yet. Thanks for reminding me :)
> 
> And yes, GitHub issues are the right place to notify us about errors, submitting new markers is easier with a simple right-click on the map.

Aaaah right. I was on mobile, while playing on Xbox xD

Good to know tho! Thnx!

**Comment by lordfiSh** [comment]
Thanks and done!
