### ISSUE TITLE
Description for Stone Eagle target

### ISSUE THREAD

**Issue by OrionRed** [lordfiSh/sniperelite5maps#12]
![image](https://github.com/lordfiSh/sniperelite5maps/assets/46463407/55a58cfa-a917-4033-8f5b-07cdaffa9d84)

The description reads "Can only be seen from the west" If the map is North = Up, then the bird is actually only visible from the East.

Also, thank you for these maps! I spend a few hours looking first, but I do eventually give up on one or two things. For SE4, I would have NEVER thought to look on that boat for an eagle!

**Comment by AtomCrafty** [comment]
Good catch, thanks! I probably couldn't make up my mind on whether to write "while looking west" or "from the east" and ended up mixing the two.

But I'm glad to hear that the maps find some use!

**Comment by AtomCrafty** [comment]
Fixed by 42dc0573c47118680dfe08ec283144287af9f8c7.
