### ISSUE TITLE
Rubble and Ruin map are empty

### ISSUE THREAD

**Issue by Ukrainiantranslator** [lordfiSh/sniperelite5maps#13]
https://sniperelite5maps.de/m08/#3/1581/2237/

**Comment by Ukrainiantranslator** [comment]
and another DLC maps too

**Comment by AtomCrafty** [comment]
We are still working on those maps. Adding the markers is a slow process. Rubble and Ruin is almost done and I've just added the DLC maps from Season Pass 2 (I only bought it a few days ago). Not sure when we will get to populating them.

**Comment by lordfiSh** [comment]
Will be closed for now, Map 08 is now filled.
