### ISSUE TITLE
Mission 4 - War Factory - Supply Crate

### ISSUE THREAD

**Issue by MTMabowels** [lordfiSh/sniperelite5maps#15]
I am re-playing **Sniper Elite 5**.  This is by far my favourite game on my PS4. Used in conjunction with your excellent interactive maps, however I find this game is doubly enjoyable.  

I realise that your maps are a work in progress and I want to help by informing you of the location of a **Supply Crate** that I came across that, as of yesterday, 20 September 2024, isn’t on your **War Factory** (Mission 4) map.

It is at the north eastern part of the map, at the north end of the Refinery building, located on the roof right above the giant round vat. I attach a screenshot showing my cursor (a little hand) at the location of the supply crate.  Hope this helps.  

I look forward to using your **Sniper Elite 6** maps when that game get released.

Best regards
![Screenshot 2024-09-20 at 17 54 50crop](https://github.com/user-attachments/assets/af302bd6-3f4a-45b8-93bf-d16c2b4dc8fa)

**Comment by lordfiSh** [comment]
Added, Thanks.

**Comment by MTMabowels** [comment]
Here’s another crop, in case you are interested.  I found **bolt cutters** at the location of the cursor. They are up on a walkway just beyond a single soldier. 

On the opposite side of the building, again up on a walkway, you show a supply crate that you say can be opened by picking or bolt cutters. It’s right beside the document “P.1000 Ratte Plans”.  In my game there is no supply crate where the supply crate is shown, instead there is an **MG42** lying on a wooden workbench next to a drilling apparatus. 

I have no idea why my game should be different this way.  Anyway, I have finished this level now, and am off to the next mission.

Best regards 

![Screenshot 2024-09-24 at 16 34 19 Bolt Cutters crop](https://github.com/user-attachments/assets/6c50f914-f8f0-4c97-bb84-fc31840645a4)

**Comment by MTMabowels** [comment]
Found a **Flare Gun** on the **Guernsey Map**. It’s upstairs at the south east side of the barn that is south western one of three barns where the personal letter _Getting Off The Island_ and _Crystal Radio_ are.
FYI - This flare gun isn’t shown in other people’s maps either.

![Screenshot 2024-09-25 at 11 22 02 Gurnsey Flare Gun](https://github.com/user-attachments/assets/fd117399-84d8-4706-825f-48d80973fe56)

**Comment by AtomCrafty** [comment]
The only items we mark are the ones highlighted in orange when you look at them, i.e. crowbars, bolt cutters, satchel charges and
some map specific items like rat bombs or poison. We've made the decision to not mark any temporary weapons since there are just too many of them and nearly every enemy is carrying one. I'm not entirely sure which category the flare gun falls in, but I'd assume it's the latter.

**Comment by MTMabowels** [comment]
Fair enough.  I’ve found another pair of unmarked bolt cutters on the Gurnsey map. They were under the north western corner of the camouflage netting directly behind the second tank.  However, I don’t recall them being highlighted like the others. You may consider that they don’t count either.

If I find anything else, bearing in mind what you have said, I will wait until the end of the map to save you from being pestered by me.   ;-) 

Best regards

Dean
